# Generated by Django 5.2.14 on 2026-05-16 21:36

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nazwa kategorii"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Tytuł")),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(blank=True, max_length=500, verbose_name="Skrót"),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Treść"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="news/images/",
                        verbose_name="Zdjęcie",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data publikacji",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Opublikowany"),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Przypięty"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="news.newscategory",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktualność",
                "verbose_name_plural": "Aktualności",
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
    ]
