# Generated by Django 5.1.3 on 2026-09-04 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=220,
                        unique=True,
                        verbose_name="Slug (adres URL)",
                    ),
                ),
                (
                    "lead",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Zajawka"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Możesz używać HTML.", verbose_name="Treść"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="articles/", verbose_name="Obrazek"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data publikacji",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Opublikowana"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aktualność",
                "verbose_name_plural": "Aktualności",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "slug",
                    models.SlugField(
                        max_length=220, unique=True, verbose_name="Slug (adres URL)"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Możesz używać HTML.", verbose_name="Treść"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Opublikowana"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Strona statyczna",
                "verbose_name_plural": "Strony statyczne",
                "ordering": ["title"],
            },
        ),
    ]
