# Generated by Django 5.1.3 on 2026-09-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="badge_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gold", "Złoty (awans, sukces)"),
                    ("green", "Zielony (szkolenie)"),
                    ("blue", "Niebieski (informacja)"),
                    ("red", "Czerwony (ważne)"),
                    ("", "Bez etykiety"),
                ],
                default="",
                max_length=10,
                verbose_name="Kolor etykiety",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="badge_label",
            field=models.CharField(
                blank=True,
                help_text="np. „Awans”, „Szkolenie”. Puste = bez etykiety.",
                max_length=40,
                verbose_name="Tekst etykiety",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="body_extended",
            field=models.TextField(
                blank=True,
                help_text="Dalsza część artykułu pod przyciskiem „Czytaj więcej”. HTML dozwolony.",
                verbose_name="Treść rozwijana",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="glyph",
            field=models.CharField(
                blank=True,
                help_text="Pojedynczy znak/emoji wyświetlany na tle kafla (np. ▲, ★, 🏐).",
                max_length=4,
                verbose_name="Symbol na kaflu",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(
                help_text="Krótki wstęp widoczny bez klikania „Czytaj więcej”. HTML dozwolony.",
                verbose_name="Treść (widoczna od razu)",
            ),
        ),
    ]
