# Generated by Django 5.1.3 on 2026-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_seed_initial_articles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.TextField(
                help_text="Krótki wstęp pokazywany na kaflu na stronie głównej. HTML dozwolony.",
                verbose_name="Zajawka (widoczna na stronie głównej)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="body_extended",
            field=models.TextField(
                blank=True,
                help_text="Dalsza część widoczna po kliknięciu „Czytaj więcej” — otwiera osobną stronę z pełnym artykułem. Zostaw puste, jeśli artykuł kończy się na zajawce (wtedy „Czytaj więcej” się nie pojawi). HTML dozwolony.",
                verbose_name="Pełna treść artykułu",
            ),
        ),
    ]
