# Generated by Django 5.2.14 on 2026-05-16 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Imię i nazwisko"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adres e-mail"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Temat")),
                ("message", models.TextField(verbose_name="Wiadomość")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Przeczytana"),
                ),
            ],
            options={
                "verbose_name": "Wiadomość kontaktowa",
                "verbose_name_plural": "Wiadomości kontaktowe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Pytanie")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Odpowiedź tekstowa"),
                            ("choice", "Wybór spośród opcji"),
                            ("yesno", "Tak / Nie"),
                        ],
                        default="text",
                        max_length=10,
                        verbose_name="Typ pytania",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Wymagane"),
                ),
            ],
            options={
                "verbose_name": "Pytanie",
                "verbose_name_plural": "Pytania",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Tytuł ankiety"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Zamknięcie"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ankieta",
                "verbose_name_plural": "Ankiety",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="Opcja")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="contact.question",
                        verbose_name="Pytanie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opcja odpowiedzi",
                "verbose_name_plural": "Opcje odpowiedzi",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="contact.survey",
                verbose_name="Ankieta",
            ),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "respondent_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail respondenta"
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="contact.survey",
                        verbose_name="Ankieta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odpowiedź na ankietę",
                "verbose_name_plural": "Odpowiedzi na ankiety",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Odpowiedź tekstowa"),
                ),
                (
                    "choice_answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contact.choice",
                        verbose_name="Wybrana opcja",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact.question",
                        verbose_name="Pytanie",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="contact.surveyresponse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Odpowiedź",
                "verbose_name_plural": "Odpowiedzi",
            },
        ),
    ]
