# Generated by Django 5.2.14 on 2026-05-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa sponsora"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sponsors/logos/",
                        verbose_name="Logo",
                    ),
                ),
                ("website_url", models.URLField(blank=True, verbose_name="Strona WWW")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("gold", "Złoty"),
                            ("silver", "Srebrny"),
                            ("bronze", "Brązowy"),
                            ("partner", "Partner"),
                        ],
                        default="partner",
                        max_length=20,
                        verbose_name="Poziom",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Sponsor",
                "verbose_name_plural": "Sponsorzy",
                "ordering": ["tier", "order", "name"],
            },
        ),
    ]
