# Generated by Django 5.2.14 on 2026-05-16 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Nazwa kategorii"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Kolejność"),
                ),
            ],
            options={
                "verbose_name": "Kategoria dokumentów",
                "verbose_name_plural": "Kategorie dokumentów",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Tytuł")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                ("file", models.FileField(upload_to="documents/", verbose_name="Plik")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data dodania"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenty",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
