# Generated by Django 5.1.3 on 2026-09-04 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nazwa"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="Opis"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Kolejność"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria dokumentu",
                "verbose_name_plural": "Kategorie dokumentów",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "file",
                    models.FileField(upload_to="documents/%Y/", verbose_name="Plik"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "published_at",
                    models.DateField(auto_now_add=True, verbose_name="Data publikacji"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, verbose_name="Widoczny na stronie"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="documents.documentcategory",
                        verbose_name="Kategoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenty",
                "ordering": ["-published_at", "-id"],
            },
        ),
    ]
