# Generated by Django 5.2.14 on 2026-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Wyróżniony (strona główna)"
            ),
        ),
    ]
