# Generated by Django 5.1.3 on 2026-09-20 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="external_url",
            field=models.CharField(
                blank=True,
                help_text="Alternatywa dla pliku — np. „/static/dokumenty/x.pdf” albo pełny adres URL do dokumentu w innym miejscu.",
                max_length=500,
                verbose_name="Adres pliku",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Prześlij plik z dysku ALBO podaj adres w polu poniżej.",
                upload_to="documents/%Y/",
                verbose_name="Plik",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="published_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Data publikacji"
            ),
        ),
    ]
