from django.test import TestCase
from django.urls import reverse

from .models import Article, StaticPage


class ArticleModelTests(TestCase):
    def test_slug_is_autogenerated_from_title(self):
        article = Article.objects.create(title="Awans sędziów", body="Treść.")
        self.assertEqual(article.slug, "awans-sedziow")

    def test_slug_falls_back_when_title_has_no_ascii(self):
        article = Article.objects.create(title="???", body="Treść.")
        self.assertEqual(article.slug, "aktualnosc")

    def test_existing_slug_is_preserved(self):
        article = Article.objects.create(
            title="Nowy tytuł", slug="rec-custom-slug", body="x"
        )
        self.assertEqual(article.slug, "rec-custom-slug")


class HomeViewTests(TestCase):
    def test_home_returns_200(self):
        response = self.client.get(reverse("pages:home"))
        self.assertEqual(response.status_code, 200)

    def test_home_lists_published_articles_only(self):
        Article.objects.create(title="Widoczna", body="x", is_published=True)
        Article.objects.create(title="Ukryta", body="x", is_published=False)
        response = self.client.get(reverse("pages:home"))
        titles = [a.title for a in response.context["articles"]]
        self.assertIn("Widoczna", titles)
        self.assertNotIn("Ukryta", titles)


class ArticleDetailViewTests(TestCase):
    def test_published_article_returns_200(self):
        article = Article.objects.create(title="Test", body="x", is_published=True)
        response = self.client.get(
            reverse("pages:article_detail", args=[article.slug])
        )
        self.assertEqual(response.status_code, 200)

    def test_unpublished_article_returns_404(self):
        article = Article.objects.create(title="Test", body="x", is_published=False)
        response = self.client.get(
            reverse("pages:article_detail", args=[article.slug])
        )
        self.assertEqual(response.status_code, 404)

    def test_missing_article_returns_404(self):
        response = self.client.get(
            reverse("pages:article_detail", args=["nie-istnieje"])
        )
        self.assertEqual(response.status_code, 404)


class StaticPageViewTests(TestCase):
    def test_published_static_page_returns_200(self):
        StaticPage.objects.create(
            title="Kontakt", slug="kontakt", body="x", is_published=True
        )
        response = self.client.get(reverse("pages:static_page", args=["kontakt"]))
        self.assertEqual(response.status_code, 200)

    def test_unpublished_static_page_returns_404(self):
        StaticPage.objects.create(
            title="Kontakt", slug="kontakt", body="x", is_published=False
        )
        response = self.client.get(reverse("pages:static_page", args=["kontakt"]))
        self.assertEqual(response.status_code, 404)


class SiteInfrastructureTests(TestCase):
    def test_robots_txt_renders(self):
        response = self.client.get("/robots.txt")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/plain")

    def test_sitemap_xml_renders(self):
        response = self.client.get("/sitemap.xml")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/xml")

    def test_admin_redirects_anonymous_to_login(self):
        response = self.client.get("/admin/")
        self.assertIn(response.status_code, (301, 302))
