from django.core import mail
from django.test import TestCase
from django.urls import reverse

from documents.models import Document, DocumentCategory

from .models import Article, StaticPage


VALID_POST = {
    "name": "Jan Kowalski",
    "email": "jan@example.com",
    "topic": "Sprawy organizacyjne",
    "message": "Dzień dobry, mam pytanie odnośnie…",
    "consent": "on",
}


class ArticleModelTests(TestCase):
    def test_slug_is_autogenerated_from_title(self):
        article = Article.objects.create(title="Awans sędziów", body="Treść.")
        self.assertEqual(article.slug, "awans-sedziow")

    def test_slug_falls_back_when_title_has_no_ascii(self):
        article = Article.objects.create(title="???", body="Treść.")
        self.assertEqual(article.slug, "aktualnosc")

    def test_existing_slug_is_preserved(self):
        article = Article.objects.create(
            title="Nowy tytuł", slug="rec-custom-slug", body="x"
        )
        self.assertEqual(article.slug, "rec-custom-slug")


class HomeViewTests(TestCase):
    def test_home_returns_200(self):
        response = self.client.get(reverse("pages:home"))
        self.assertEqual(response.status_code, 200)

    def test_home_lists_published_articles_only(self):
        Article.objects.create(title="Widoczna", body="x", is_published=True)
        Article.objects.create(title="Ukryta", body="x", is_published=False)
        response = self.client.get(reverse("pages:home"))
        titles = [a.title for a in response.context["articles"]]
        self.assertIn("Widoczna", titles)
        self.assertNotIn("Ukryta", titles)


class ArticleDetailViewTests(TestCase):
    def test_published_article_returns_200(self):
        article = Article.objects.create(title="Test", body="x", is_published=True)
        response = self.client.get(
            reverse("pages:article_detail", args=[article.slug])
        )
        self.assertEqual(response.status_code, 200)

    def test_unpublished_article_returns_404(self):
        article = Article.objects.create(title="Test", body="x", is_published=False)
        response = self.client.get(
            reverse("pages:article_detail", args=[article.slug])
        )
        self.assertEqual(response.status_code, 404)

    def test_missing_article_returns_404(self):
        response = self.client.get(
            reverse("pages:article_detail", args=["nie-istnieje"])
        )
        self.assertEqual(response.status_code, 404)


class StaticPageViewTests(TestCase):
    def test_published_static_page_returns_200(self):
        StaticPage.objects.create(
            title="Kontakt", slug="kontakt", body="x", is_published=True
        )
        response = self.client.get(reverse("pages:static_page", args=["kontakt"]))
        self.assertEqual(response.status_code, 200)

    def test_unpublished_static_page_returns_404(self):
        StaticPage.objects.create(
            title="Kontakt", slug="kontakt", body="x", is_published=False
        )
        response = self.client.get(reverse("pages:static_page", args=["kontakt"]))
        self.assertEqual(response.status_code, 404)


class ArticleListViewTests(TestCase):
    """Nowa strona /aktualnosci/ — indeks wpisów."""

    def test_list_returns_200(self):
        response = self.client.get(reverse("pages:article_list"))
        self.assertEqual(response.status_code, 200)

    def test_list_shows_only_published(self):
        Article.objects.create(title="A", body="x", is_published=True)
        Article.objects.create(title="B", body="x", is_published=False)
        response = self.client.get(reverse("pages:article_list"))
        titles = {a.title for a in response.context["articles"]}
        self.assertIn("A", titles)
        self.assertNotIn("B", titles)

    def test_list_links_to_detail_pages(self):
        art = Article.objects.create(title="Linkowana", body="x")
        response = self.client.get(reverse("pages:article_list"))
        expected_href = reverse("pages:article_detail", args=[art.slug])
        self.assertContains(response, f'href="{expected_href}"')

    def test_preview_decodes_html_entities(self):
        # TinyMCE potrafi zapisać „ó” jako &oacute; — podgląd ma pokazać literę.
        Article.objects.create(title="Encje", body="<p>Sędziowie &oacute;semki&nbsp;i &bdquo;nowi&rdquo;</p>")
        for url in (reverse("pages:article_list"), reverse("pages:home")):
            response = self.client.get(url)
            self.assertContains(response, "Sędziowie ósemki i „nowi”")
            self.assertNotContains(response, "&amp;oacute;")


class HomeDocumentsSectionTests(TestCase):
    """Sekcja Dokumenty na home musi wciągać dane z bazy (seed 0003)."""

    def test_home_context_has_doc_categories(self):
        response = self.client.get(reverse("pages:home"))
        # Seed migracji 0003 daje 4 kanoniczne kategorie.
        slugs = {c.slug for c in response.context["doc_categories"]}
        for expected in {"przepisy-gry", "wytyczne-i-instrukcje",
                         "materialy-szkoleniowe", "komunikaty"}:
            self.assertIn(expected, slugs)

    def test_home_renders_document_link_from_db(self):
        # Dodaj dokument w istniejącej seedowanej kategorii i sprawdź,
        # że pojawi się jego link na home.
        cat = DocumentCategory.objects.get(slug="komunikaty")
        doc = Document.objects.create(
            title="Test — dodany w teście",
            category=cat,
            external_url="/static/dokumenty/test.pdf",
            description="opis testowy",
        )
        response = self.client.get(reverse("pages:home"))
        self.assertContains(response, doc.title)
        self.assertContains(response, doc.external_url)

    def test_unpublished_document_hidden(self):
        cat = DocumentCategory.objects.get(slug="komunikaty")
        Document.objects.create(
            title="Schowany dokument",
            category=cat,
            external_url="/static/dokumenty/nope.pdf",
            is_published=False,
        )
        response = self.client.get(reverse("pages:home"))
        self.assertNotContains(response, "Schowany dokument")


class ContactSubmitTests(TestCase):
    url = reverse("pages:contact_submit") if hasattr(reverse, "__call__") else "/kontakt/wyslij/"

    def setUp(self):
        # locmem backend gromadzi wiadomości w mail.outbox; czyścimy dla higieny.
        mail.outbox = []

    def test_get_returns_405(self):
        response = self.client.get(reverse("pages:contact_submit"))
        self.assertEqual(response.status_code, 405)

    def test_valid_post_sends_email(self):
        response = self.client.post(reverse("pages:contact_submit"), VALID_POST)
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"ok": True})
        self.assertEqual(len(mail.outbox), 1)
        m = mail.outbox[0]
        self.assertEqual(m.to, ["ws@szps.pl"])
        self.assertIn("Sprawy organizacyjne", m.subject)
        self.assertIn("Jan Kowalski", m.body)
        self.assertIn("jan@example.com", m.body)
        # Reply-To pozwala kliknąć "Odpowiedz" i trafić na formularzowego usera.
        self.assertEqual(m.reply_to, ["jan@example.com"])

    def test_missing_field_returns_400(self):
        bad = {**VALID_POST, "email": "nope"}
        response = self.client.post(reverse("pages:contact_submit"), bad)
        self.assertEqual(response.status_code, 400)
        self.assertIn("email", response.json()["errors"])
        self.assertEqual(len(mail.outbox), 0)

    def test_missing_consent_returns_400(self):
        bad = {**VALID_POST}
        bad.pop("consent")
        response = self.client.post(reverse("pages:contact_submit"), bad)
        self.assertEqual(response.status_code, 400)
        self.assertIn("consent", response.json()["errors"])
        self.assertEqual(len(mail.outbox), 0)

    def test_unknown_topic_rejected(self):
        bad = {**VALID_POST, "topic": "Prześlij zdjęcie karty kredytowej"}
        response = self.client.post(reverse("pages:contact_submit"), bad)
        self.assertEqual(response.status_code, 400)
        self.assertIn("topic", response.json()["errors"])
        self.assertEqual(len(mail.outbox), 0)

    def test_honeypot_silently_accepts_and_drops(self):
        # Bot wypełnił ukryte pole `website` — udajemy sukces, nic nie wysyłamy.
        response = self.client.post(
            reverse("pages:contact_submit"),
            {**VALID_POST, "website": "https://spam.example"},
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.json(), {"ok": True})
        self.assertEqual(len(mail.outbox), 0)


class SiteInfrastructureTests(TestCase):
    def test_robots_txt_renders(self):
        response = self.client.get("/robots.txt")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "text/plain")

    def test_sitemap_xml_renders(self):
        response = self.client.get("/sitemap.xml")
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response["Content-Type"], "application/xml")

    def test_admin_redirects_anonymous_to_login(self):
        response = self.client.get("/admin/")
        self.assertIn(response.status_code, (301, 302))
