# Generated by Django 5.1.3 on 2026-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Imię")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Nazwisko"),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="np. Przewodniczący, Sekretarz, Członek",
                        max_length=150,
                        verbose_name="Funkcja",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="board/", verbose_name="Zdjęcie"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Krótki opis")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Niższa liczba = wyżej na liście.",
                        verbose_name="Kolejność",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Członek wydziału",
                "verbose_name_plural": "Skład wydziału",
                "ordering": ["order", "last_name", "first_name"],
            },
        ),
    ]
