# Generated by Django 5.1.3 on 2026-09-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_seed_initial_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={
                "ordering": ["order", "last_name", "first_name"],
                "verbose_name": "Członek wydziału",
                "verbose_name_plural": "Skład wydziału",
            },
        ),
    ]
