# Generated by Django 5.1.3 on 2026-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_boardmember_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={
                "ordering": ["order", "last_name", "first_name"],
                "verbose_name": "Członek Wydziału",
                "verbose_name_plural": "Skład Wydziału",
            },
        ),
    ]
